-- CREATE TABLE users (
--  id INT AUTO_INCREMENT PRIMARY KEY,
--  name VARCHAR(255) NOT NULL,
--  username VARCHAR(255) NOT NULL,
--  email VARCHAR(255) NOT NULL,
--  password VARCHAR(255) NOT NULL
-- );




-- CREATE TABLE centers (
--  id INT AUTO_INCREMENT PRIMARY KEY,
--  name VARCHAR(255) NOT NULL,
--  location VARCHAR(255) NOT NULL,
--  address TEXT NOT NULL
-- );